In [1]:
import pandas as pd

### openbookQA dataset

In [13]:
splits = {'train': 'additional/train-00000-of-00001.parquet', 'validation': 'additional/validation-00000-of-00001.parquet', 'test': 'additional/test-00000-of-00001.parquet'}
openbookqa_dataset = pd.read_parquet("hf://datasets/allenai/openbookqa/" + splits["train"])

In [14]:
openbookqa_dataset.head()

,id,question_stem,choices,answerKey,fact1,humanScore,clarity,turkIdAnonymized
0,7-980,The sun is responsible for,"{'text': ['puppies learning new tricks', 'chil...",D,the sun is the source of energy for physical c...,1.0,2.0,b356d338b7
1,7-584,When standing miles away from Mount Rushmore,"{'text': ['the mountains seem very close', 'th...",D,"as distance to an object increases , that obje...",1.0,1.4,b356d338b7
2,7-870,When food is reduced in the stomach,"{'text': ['the mind needs time to digest', 'ta...",C,digestion is when stomach acid breaks down food,1.0,1.6,b356d338b7
3,7-321,Stars are,"{'text': ['warm lights that float', 'made out ...",C,a star is made of gases,1.0,1.6,b356d338b7
4,9-732,You can make a telescope with a,"{'text': ['straw', 'Glass', 'Candle', 'mailing...",D,Galileo Galilei made improvements to the teles...,0.8,1.0,cee82219a0

In [15]:
openbookqa_dataset = openbookqa_dataset.drop(columns=['id', 'turkIdAnonymized'])  # Drop unnecessary columns
openbookqa_dataset.head()

,question_stem,choices,answerKey,fact1,humanScore,clarity
0,The sun is responsible for,"{'text': ['puppies learning new tricks', 'chil...",D,the sun is the source of energy for physical c...,1.0,2.0
1,When standing miles away from Mount Rushmore,"{'text': ['the mountains seem very close', 'th...",D,"as distance to an object increases , that obje...",1.0,1.4
2,When food is reduced in the stomach,"{'text': ['the mind needs time to digest', 'ta...",C,digestion is when stomach acid breaks down food,1.0,1.6
3,Stars are,"{'text': ['warm lights that float', 'made out ...",C,a star is made of gases,1.0,1.6
4,You can make a telescope with a,"{'text': ['straw', 'Glass', 'Candle', 'mailing...",D,Galileo Galilei made improvements to the teles...,0.8,1.0

In [25]:
openbookqa_dataset.to_csv("../Data/General culture/openbookqa_dataset.csv", index=False)  # Save the cleaned dataset to a CSV file

### SQUAD DATASET

In [26]:
splits = {'train': 'plain_text/train-00000-of-00001.parquet', 'validation': 'plain_text/validation-00000-of-00001.parquet'}
squad_dataset = pd.read_parquet("hf://datasets/rajpurkar/squad/" + splits["train"])

In [27]:
squad_dataset.head()

,id,title,context,question,answers
0,5733be284776f41900661182,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",To whom did the Virgin Mary allegedly appear i...,"{'text': ['Saint Bernadette Soubirous'], 'answ..."
1,5733be284776f4190066117f,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What is in front of the Notre Dame Main Building?,"{'text': ['a copper statue of Christ'], 'answe..."
2,5733be284776f41900661180,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",The Basilica of the Sacred heart at Notre Dame...,"{'text': ['the Main Building'], 'answer_start'..."
3,5733be284776f41900661181,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What is the Grotto at Notre Dame?,{'text': ['a Marian place of prayer and reflec...
4,5733be284776f4190066117e,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What sits on top of the Main Building at Notre...,{'text': ['a golden statue of the Virgin Mary'...

In [ ]:
squad_dataset = squad_dataset.drop(columns=['id', 'title', 'context'])  # Drop unnecessary columns

In [32]:
squad_dataset['answers'].head()[0]
squad_dataset.to_csv("../Data/General culture/squad_dataset.csv", index=False)  # Save the cleaned dataset to a CSV file

### quartz Dataset

In [34]:
splits = {'train': 'data/train-00000-of-00001.parquet', 'test': 'data/test-00000-of-00001.parquet', 'validation': 'data/validation-00000-of-00001.parquet'}
quart_dataset = pd.read_parquet("hf://datasets/allenai/quartz/" + splits["train"])
quart_dataset.to_csv("../Data/QuaRTz/quartz_dataset.csv", index=False)  # Save the cleaned dataset to a CSV file